title: Aryaman Jha
description: "My Homepage"
url: "https://aryaman-jha.github.io/Aryaman_Jha"

# paginate: 5
# paginate_path: "/page:num/"
# plugins: [jekyll-paginate]

markdown: kramdown
highlighter: rouge

social-accounts:
  facebook: "aryaman.jha.iitk"
  googleplus: "110887746255485044848"
  github: "aryaman-jha"
  email: "rmnjha@iitk.ac.in"
  linkedin: "in/aryaman-jha"

author:
  name: "Aryaman Jha"
  jobTitle: "Third Year UnderGraduate, Physics"
  orgName: "IIT Kanpur"
  orgURL: "https://www.iitk.ac.in/"

sass:
  sass_dir: _sass
  style: :compressed

# google_analytics:
# disqus_shortname:
